# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 James Ray Hawkins

"""
MMLKG Adapter -- Mizar Mathematical Library Knowledge Graph

Loads the MMLKG (Mizar Mathematical Library Knowledge Graph).
The MMLKG provides ~60K articles with dependency edges between theorems.

Source: https://mmlkg.uwb.edu.pl/ or https://github.com/lszeremeta/mizgra
Format: GraphML (generated by mizgra from ESX files)

The adapter can:
1. Load pre-generated GraphML files
2. Parse ESX files directly (simplified extraction)
3. Run demo data if no source available

Node types: theorems, definitions, notations, schemes
Edge types: BROADER (hierarchical), MEMBER (parent-child), RELATED (references)

To generate GraphML from ESX files:
    pip install mizgra
    mizgra /path/to/esx_mml /path/to/mml.lar > mmlkg.graphml
"""

from __future__ import annotations

import json
import os
import re
from typing import Any, Dict, List, Optional, Set, Tuple

from core.types import Object, Morphism
from core.category import Category
from domains.mathematics.schema import (
    theorem_object,
    definition_object,
    proof_morphism,
)


class MMLKGAdapter:
    """
    Loads MMLKG data into a KOMPOSOS-IV Category.

    Usage:
        adapter = MMLKGAdapter("/path/to/mmlkg/data")
        result = adapter.load_into(category)
        print(f"Loaded {result['objects']} objects, {result['morphisms']} morphisms")
    """

    def __init__(self, data_path: Optional[str] = None):
        """
        Args:
            data_path: Path to MMLKG data directory or GraphML file.
                       Can be:
                       - Path to .graphml file
                       - Path to directory with ESX files (esx_mml/)
                       - None for demo data
        """
        self.data_path = data_path
        self._objects: List[Object] = []
        self._morphisms: List[Morphism] = []
        self._parsed = False
        self._theorem_ids: Set[str] = set()

    def load_into(self, category: Category) -> Dict[str, int]:
        """
        Parse MMLKG data and load into the given Category.

        Returns dict with counts: {"objects": N, "morphisms": M}
        """
        if not self._parsed:
            self._parse()

        result = category.bulk_add(self._objects, self._morphisms)
        return result

    def _parse(self):
        """Parse MMLKG files into Objects and Morphisms."""
        if self.data_path and os.path.exists(self.data_path):
            self._parse_from_files()
        else:
            self._load_demo_data()
        self._parsed = True

    def _parse_from_files(self):
        """
        Parse actual MMLKG files.

        Tries in order:
        1. GraphML file (.graphml, .graphml.gz)
        2. ESX files directory (esx_mml/ with mml.lar)
        3. JSON/CSV format (nodes.json, edges.json)
        """
        # Check for GraphML file
        if os.path.isfile(self.data_path):
            if self.data_path.endswith((".graphml", ".graphml.gz")):
                self._parse_graphml(self.data_path)
                return

        # Check for GraphML in directory
        if os.path.isdir(self.data_path):
            for ext in ["*.graphml", "*.graphml.gz"]:
                import glob
                graphml_files = glob.glob(os.path.join(self.data_path, ext))
                if graphml_files:
                    self._parse_graphml(graphml_files[0])
                    return

            # Check for ESX files
            esx_dir = os.path.join(self.data_path, "esx_mml")
            mml_lar = os.path.join(self.data_path, "mml.lar")
            if os.path.isdir(esx_dir) and os.path.exists(mml_lar):
                self._parse_esx(esx_dir, mml_lar)
                return

            # Check for JSON format
            nodes_path = os.path.join(self.data_path, "nodes.json")
            edges_path = os.path.join(self.data_path, "edges.json")
            if os.path.exists(nodes_path):
                self._parse_json(nodes_path, edges_path)
                return

            # Check for CSV format
            csv_nodes = os.path.join(self.data_path, "nodes.csv")
            if os.path.exists(csv_nodes):
                self._parse_csv(csv_nodes, os.path.join(self.data_path, "edges.csv"))
                return

        print(f"MMLKG: No recognized data format found in {self.data_path}")
        print("Expected: .graphml file, or esx_mml/ directory with mml.lar")
        self._load_demo_data()

    def _parse_graphml(self, graphml_path: str):
        """
        Parse GraphML format MMLKG.

        GraphML structure:
        <graphml>
          <key id="label" for="node" attr.name="label" attr.type="string"/>
          <key id="type" for="node" attr.name="type" attr.type="string"/>
          <graph edgedefault="directed">
            <node id="TOPREAL7:1">
              <data key="label">Intermediate Value Theorem</data>
              <data key="type">theorem</data>
            </node>
            <edge source="TOPREAL7:1" target="COMPTS_1:1">
              <data key="type">RELATED</data>
            </edge>
          </graph>
        </graphml>
        """
        print(f"MMLKG: Parsing GraphML from {graphml_path}")

        # Handle gzipped files
        import gzip
        open_func = gzip.open if graphml_path.endswith(".gz") else open

        try:
            import xml.etree.ElementTree as ET
            with open_func(graphml_path, "rt", encoding="utf-8") as f:
                tree = ET.parse(f)
            root = tree.getroot()

            # Find the graph element
            ns = {"graphml": "http://graphml.graphdrawing.org/xmlns"}
            graph_elem = root.find(".//graphml:graph", ns)
            if graph_elem is None:
                graph_elem = root.find(".//graph")

            if graph_elem is None:
                # Try without namespace
                for elem in root:
                    if elem.tag.endswith("graph") or "graph" in elem.tag:
                        graph_elem = elem
                        break

            if graph_elem is None:
                print("MMLKG: No graph element found in GraphML")
                self._load_demo_data()
                return

            # Parse nodes
            node_count = 0
            for node in graph_elem:
                if node.tag.endswith("node") or node.tag == "node":
                    node_id = node.get("id", "")
                    if not node_id:
                        continue

                    label = ""
                    node_type = "theorem"
                    field = "unknown"

                    for data in node:
                        key = data.get("key", "")
                        if key == "label" or "label" in key.lower():
                            label = data.text or ""
                        elif key == "type" or "type" in key.lower():
                            node_type = (data.text or "theorem").lower()

                    # Extract field from Mizar article ID (e.g., TOPREAL7 -> general_topology)
                    field = self._mizar_id_to_field(node_id)

                    if node_type in ("theorem", "lemma", "proposition"):
                        obj = theorem_object(
                            name=node_id,
                            statement=label[:500] if label else "",
                            field=field,
                            source="mmlkg",
                        )
                    elif node_type == "definition":
                        obj = definition_object(
                            name=node_id,
                            statement=label[:500] if label else "",
                            field=field,
                            source="mmlkg",
                        )
                    else:
                        obj = Object(
                            name=node_id,
                            type_name=node_type.capitalize(),
                            metadata={"statement": label, "field": field},
                            provenance="mmlkg",
                        )

                    self._objects.append(obj)
                    self._theorem_ids.add(node_id)
                    node_count += 1

            print(f"MMLKG: Loaded {node_count} nodes")

            # Parse edges
            edge_count = 0
            for edge in graph_elem:
                if edge.tag.endswith("edge") or edge.tag == "edge":
                    src = edge.get("source", "")
                    tgt = edge.get("target", "")

                    if not src or not tgt:
                        continue

                    edge_type = "RELATED"
                    for data in edge:
                        key = data.get("key", "")
                        if key == "type" or "type" in key.lower():
                            edge_type = (data.text or "RELATED").upper()

                    confidence = self._edge_type_confidence(edge_type)

                    self._morphisms.append(
                        proof_morphism(
                            name=f"mmlkg:{src}->{tgt}",
                            source_thm=src,
                            target_thm=tgt,
                            confidence=confidence,
                            proof_type=edge_type.lower(),
                            source="mmlkg",
                        )
                    )
                    edge_count += 1

            print(f"MMLKG: Loaded {edge_count} edges")

        except Exception as e:
            print(f"MMLKG: Error parsing GraphML: {e}")
            self._load_demo_data()

    def _parse_esx(self, esx_dir: str, mml_lar: str):
        """
        Parse ESX files directly (simplified extraction).

        ESX files contain Mizar article data in XML format.
        mml.lar contains the article dependency information.

        This is a simplified parser that extracts theorem/definition IDs
        and creates basic dependency morphisms from article dependencies.
        """
        print(f"MMLKG: Parsing ESX files from {esx_dir}")

        # Parse mml.lar for article dependencies
        article_deps = self._parse_mml_lar(mml_lar)
        print(f"MMLKG: Found {len(article_deps)} article dependencies")

        # Parse ESX files for theorems/definitions
        theorem_count = 0
        for root, dirs, files in os.walk(esx_dir):
            for fname in files:
                if not fname.endswith(".esx"):
                    continue

                filepath = os.path.join(root, fname)
                try:
                    count = self._parse_esx_file(filepath)
                    theorem_count += count
                except Exception:
                    continue

        print(f"MMLKG: Extracted {theorem_count} theorems/definitions from ESX")

        # Create morphisms from article dependencies
        morphism_count = 0
        for article, deps in article_deps.items():
            # Find theorems in this article
            article_theorems = [
                obj.name for obj in self._objects
                if obj.name.startswith(article.split(".")[0])
            ][:10]  # Limit to avoid explosion

            for dep_article in deps:
                dep_theorems = [
                    obj.name for obj in self._objects
                    if obj.name.startswith(dep_article.split(".")[0])
                ][:5]

                for src in article_theorems[:3]:
                    for tgt in dep_theorems:
                        if src != tgt:
                            self._morphisms.append(
                                proof_morphism(
                                    name=f"mmlkg:{src}->{tgt}",
                                    source_thm=src,
                                    target_thm=tgt,
                                    confidence=0.8,
                                    proof_type="article_dependency",
                                    source="mmlkg",
                                )
                            )
                            morphism_count += 1

        print(f"MMLKG: Created {morphism_count} dependency morphisms")

    def _parse_mml_lar(self, mml_lar: str) -> Dict[str, List[str]]:
        """
        Parse mml.lar file for article dependencies.

        Format (one article per line):
        ARTICLE_ID: DEP1 DEP2 DEP3 ...
        """
        article_deps: Dict[str, List[str]] = {}

        try:
            with open(mml_lar, "r", encoding="utf-8", errors="ignore") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue

                    # Parse "ARTICLE: DEP1 DEP2 ..."
                    if ":" in line:
                        parts = line.split(":", 1)
                        article = parts[0].strip()
                        deps_str = parts[1].strip() if len(parts) > 1 else ""
                        deps = [d.strip() for d in deps_str.split() if d.strip()]
                        article_deps[article] = deps
        except Exception as e:
            print(f"MMLKG: Error parsing mml.lar: {e}")

        return article_deps

    def _parse_esx_file(self, filepath: str) -> int:
        """
        Parse a single ESX file for theorems and definitions.

        Returns count of objects extracted.
        """
        import xml.etree.ElementTree as ET

        count = 0
        try:
            tree = ET.parse(filepath)
            root = tree.getroot()

            # ESX files have various element types for theorems, definitions, etc.
            # Look for common patterns
            for elem in root.iter():
                tag = elem.tag.lower()

                # Check for theorem-like elements
                if any(kw in tag for kw in ["theorem", "lemma", "proposition", "statement"]):
                    item_id = elem.get("id", elem.get("label", ""))
                    if item_id:
                        content = elem.text or ""
                        for child in elem:
                            if child.text:
                                content += " " + (child.text or "")

                        field = self._mizar_id_to_field(item_id)
                        obj = theorem_object(
                            name=item_id,
                            statement=content[:500],
                            field=field,
                            source="mmlkg",
                        )
                        self._objects.append(obj)
                        self._theorem_ids.add(item_id)
                        count += 1

                # Check for definition elements
                elif any(kw in tag for kw in ["definition", "def"]):
                    item_id = elem.get("id", elem.get("label", ""))
                    if item_id:
                        content = elem.text or ""
                        for child in elem:
                            if child.text:
                                content += " " + (child.text or "")

                        field = self._mizar_id_to_field(item_id)
                        obj = definition_object(
                            name=item_id,
                            statement=content[:500],
                            field=field,
                            source="mmlkg",
                        )
                        self._objects.append(obj)
                        self._theorem_ids.add(item_id)
                        count += 1

        except Exception:
            pass

        return count

    def _parse_json(self, nodes_path: str, edges_path: Optional[str]):
        """Parse JSON format MMLKG data."""
        with open(nodes_path, "r", encoding="utf-8") as f:
            nodes = json.load(f)
        for node in nodes:
            node_id = node.get("id", "")
            node_type = node.get("type", "theorem").lower()
            label = node.get("label", node_id)
            field = node.get("field", "unknown")

            if node_type in ("theorem", "lemma", "proposition"):
                obj = theorem_object(
                    name=node_id,
                    statement=label,
                    field=field,
                    source="mmlkg",
                )
            elif node_type == "definition":
                obj = definition_object(
                    name=node_id,
                    statement=label,
                    field=field,
                    source="mmlkg",
                )
            else:
                obj = Object(
                    name=node_id,
                    type_name=node_type.capitalize(),
                    metadata={"statement": label, "field": field},
                    provenance="mmlkg",
                )
            self._objects.append(obj)

        if edges_path and os.path.exists(edges_path):
            with open(edges_path, "r", encoding="utf-8") as f:
                edges = json.load(f)
            for edge in edges:
                src = edge.get("source", "")
                tgt = edge.get("target", "")
                edge_type = edge.get("type", "RELATED")
                confidence = self._edge_type_confidence(edge_type)

                self._morphisms.append(
                    proof_morphism(
                        name=f"mmlkg:{src}->{tgt}",
                        source_thm=src,
                        target_thm=tgt,
                        confidence=confidence,
                        proof_type=edge_type.lower(),
                        source="mmlkg",
                    )
                )

    def _parse_csv(self, nodes_path: str, edges_path: Optional[str]):
        """Parse CSV-format MMLKG data."""
        import csv

        with open(nodes_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                node_id = row.get("id", row.get("name", ""))
                if not node_id:
                    continue
                self._objects.append(
                    theorem_object(
                        name=node_id,
                        statement=row.get("label", ""),
                        field=row.get("field", "unknown"),
                        source="mmlkg",
                    )
                )

        if edges_path and os.path.exists(edges_path):
            with open(edges_path, "r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    src = row.get("source", "")
                    tgt = row.get("target", "")
                    if src and tgt:
                        self._morphisms.append(
                            proof_morphism(
                                name=f"mmlkg:{src}->{tgt}",
                                source_thm=src,
                                target_thm=tgt,
                                source="mmlkg",
                            )
                        )

    def _mizar_id_to_field(self, mizar_id: str) -> str:
        """
        Map Mizar article ID to mathematical field.

        Examples:
            TOPREAL7:1 -> general_topology
            ALGSTR_0:def1 -> group_theory
            NAT_1:def1 -> number_theory
        """
        # Extract article prefix (before colon or underscore)
        article = mizar_id.split(":")[0] if ":" in mizar_id else mizar_id
        prefix = article.split("_")[0] if "_" in article else article

        # Map common Mizar article prefixes to fields
        field_map = {
            "TOPREAL": "general_topology",
            "COMPTS": "general_topology",
            "METRIC": "general_topology",
            "PCOMPS": "general_topology",
            "ALGSTR": "group_theory",
            "GROUP": "group_theory",
            "RING": "commutative_algebra",
            "FIELD": "field_theory",
            "VECTSP": "linear_algebra",
            "RLVECT": "linear_algebra",
            "MATRIX": "linear_algebra",
            "NAT": "number_theory",
            "INT": "number_theory",
            "RAT": "number_theory",
            "REAL": "real_analysis",
            "COMPLEX": "complex_analysis",
            "SEQ": "real_analysis",
            "SERIES": "real_analysis",
            "MEASURE": "measure_theory",
            "INTEGRA": "measure_theory",
            "PROB": "probability",
            "STAT": "statistics",
            "FUNCT": "logic_foundations",
            "ZFMISC": "logic_foundations",
            "SETFAM": "logic_foundations",
            "RELAT": "logic_foundations",
            "BOOLE": "logic_foundations",
            "FINSET": "combinatorics",
            "GRAPH": "combinatorics",
            "TREES": "combinatorics",
            "CAT": "category_theory",
            "FUNCTOR": "category_theory",
            "DIFF": "differential_geometry",
            "MANIFOLD": "differential_geometry",
        }

        return field_map.get(prefix.upper(), "unknown")

    def _edge_type_confidence(self, edge_type: str) -> float:
        """Return confidence score based on edge type."""
        edge_type = edge_type.upper()
        if edge_type == "BROADER":
            return 1.0  # Hierarchical - strongest
        elif edge_type == "MEMBER":
            return 0.95  # Parent-child - strong
        elif edge_type == "RELATED":
            return 0.8  # Reference - medium
        else:
            return 0.7  # Unknown - lower confidence

    def _load_demo_data(self):
        """Load a small demo dataset for testing without real data."""
        # 10 representative Mizar theorems spanning multiple fields
        demo_theorems = [
            ("TOPREAL7:1", "Intermediate Value Theorem", "general_topology"),
            ("ALGSTR_0:def1", "Group definition", "group_theory"),
            ("COMPTS_1:1", "Compact space theorem", "general_topology"),
            ("FUNCT_1:def1", "Function definition", "logic_foundations"),
            ("NAT_1:def1", "Natural number definition", "number_theory"),
            ("METRIC_1:1", "Metric space completeness", "general_topology"),
            ("RLVECT_1:def1", "Vector space definition", "linear_algebra"),
            ("RING_1:def1", "Ring definition", "commutative_algebra"),
            ("ZFMISC_1:1", "Set union theorem", "logic_foundations"),
            ("FINSET_1:1", "Finite set theorem", "combinatorics"),
        ]

        for name, statement, field in demo_theorems:
            self._objects.append(
                theorem_object(name=name, statement=statement, field=field, source="mmlkg")
            )

        # Dependencies (edges)
        demo_deps = [
            ("TOPREAL7:1", "COMPTS_1:1", 0.9),
            ("TOPREAL7:1", "METRIC_1:1", 0.8),
            ("COMPTS_1:1", "METRIC_1:1", 0.85),
            ("ALGSTR_0:def1", "FUNCT_1:def1", 0.95),
            ("RLVECT_1:def1", "ALGSTR_0:def1", 0.9),
            ("RING_1:def1", "ALGSTR_0:def1", 0.9),
            ("NAT_1:def1", "ZFMISC_1:1", 0.95),
            ("FINSET_1:1", "NAT_1:def1", 0.85),
            ("FINSET_1:1", "ZFMISC_1:1", 0.8),
        ]

        for src, tgt, conf in demo_deps:
            self._morphisms.append(
                proof_morphism(
                    name=f"mmlkg:{src}->{tgt}",
                    source_thm=src,
                    target_thm=tgt,
                    confidence=conf,
                    source="mmlkg",
                )
            )

    def inspect(self, n: int = 10) -> Dict[str, Any]:
        """Print N sample objects and morphisms for data inspection."""
        if not self._parsed:
            self._parse()

        return {
            "total_objects": len(self._objects),
            "total_morphisms": len(self._morphisms),
            "sample_objects": [
                {"name": o.name, "type": o.type_name, "field": o.metadata.get("field", "")}
                for o in self._objects[:n]
            ],
            "sample_morphisms": [
                {"name": m.name, "source": m.source, "target": m.target, "confidence": m.confidence}
                for m in self._morphisms[:n]
            ],
        }
